### ISSUE TITLE
The AD groups are not populated with users

### ISSUE THREAD

**Issue by hbagarich** [Acceleratio/SPDG#6]
Created AD groups do not have any members. The only log errors I get is that the object already exists.
Some groups are created without errors but they are also without members.
The target environment is SharePoint 2016 and domain controller on Windows Server 2012R2

The relevant entries from session log:

8/2/2016 10:00:22 AM	Created 0/91 groups.
8/2/2016 10:00:22 AM	Created 1/91 groups.
8/2/2016 10:00:22 AM	Created 2/91 groups.
8/2/2016 10:00:22 AM	ERROR OCCURED: The object already exists.

   at System.DirectoryServices.AccountManagement.SDSUtils.ApplyChangesToDirectory(Principal p, StoreCtx storeCtx, GroupMembershipUpdater updateGroupMembership, NetCred credentials, AuthenticationTypes authTypes)
   at System.DirectoryServices.AccountManagement.SDSUtils.InsertPrincipal(Principal p, StoreCtx storeCtx, GroupMembershipUpdater updateGroupMembership, NetCred credentials, AuthenticationTypes authTypes, Boolean needToSetPassword)
   at System.DirectoryServices.AccountManagement.ADStoreCtx.Insert(Principal p)
   at System.DirectoryServices.AccountManagement.Principal.Save()
   at Acceleratio.SPDG.Generator.Server.GenerationTasks.CreateUsersAndGroupsGenerationTask.createGroups(String domain, String ou, Int32 numOfGroups) in E:\TeamCity\Acceleratio.SPDG\Release\src\Acceleratio.SPDG.Generator.Server\GenerationTasks\CreateUsersAndGroupsGenerationTask.cs:line 119
8/2/2016 10:00:22 AM	Created 4/91 groups.

**Comment by hbagarich** [comment]
This was fixed with https://github.com/Acceleratio/SPDG/commit/39951965b7c36c3401a9178b3aaa19ce2cf513a1
